# Generated by Django 5.1.2 on 2024-11-09 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant Admin'), ('inventory_manager', 'Inventory Manager'), ('order_processor', 'Order Processor'), ('customer_service', 'Customer Service'), ('marketing_specialist', 'Marketing Specialist'), ('customer', 'Customer')], max_length=100, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'db_table': 'tenant_user',
            },
        ),
        migrations.CreateModel(
            name='TenantUserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_status', models.CharField(choices=[(None, 'Not yet'), ('send', 'Send'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resend', 'Resend')], max_length=100, verbose_name='Invitation status')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='TenantUsers.tenantuser', verbose_name='Invited by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='TenantUsers.tenantuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tenant User invitation',
                'verbose_name_plural': 'Tenant User invitations',
                'db_table': 'tenant_user_invitation',
            },
        ),
    ]
