# Generated by Django 5.1.2 on 2024-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuserinvitation',
            name='secret_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuserinvitation',
            name='invitation_status',
            field=models.CharField(choices=[(None, 'Not yet'), ('pending', 'Pending'), ('send', 'Send'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resend', 'Resend')], max_length=100, verbose_name='Invitation status'),
        ),
    ]
