# Generated by Django 5.1.2 on 2024-10-27 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Authentication',
                'verbose_name_plural': 'OTP Authentication',
                'db_table': 'otp_authentication',
                'indexes': [models.Index(fields=['user'], name='otp_authent_user_id_7d6a96_idx')],
            },
        ),
    ]
