# Generated by Django 5.1.2 on 2024-10-31 14:38

import UserAuth.utils
import django.db.models.deletion
import pyotp
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=128)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('otp_2fa_enabled', models.BooleanField(default=False)),
                ('is_recovery_generated', models.BooleanField(default=False)),
                ('recovery_email', models.EmailField(max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authentication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication',
                'verbose_name_plural': 'Authentication',
                'db_table': 'authentication',
            },
        ),
        migrations.CreateModel(
            name='HOTPAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_for', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('secret', models.CharField(default=pyotp.random_base32, editable=False, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('last_used', models.DateTimeField(null=True)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotp_authentications', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'HOTP Authentication',
                'verbose_name_plural': 'HOTP Authentication',
                'db_table': 'hotp_authentication',
            },
        ),
        migrations.CreateModel(
            name='IncompleteLoginSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_session', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Incomplete Login Session',
                'verbose_name_plural': 'Incomplete Login Sessions',
                'db_table': 'incomplete_sessions',
            },
        ),
        migrations.CreateModel(
            name='OTPAuthentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128, null=True)),
                ('otp_purpose', models.PositiveSmallIntegerField(choices=[(1, 'Verify Email'), (2, 'Second Step Verification')])),
                ('expires_at', models.DateTimeField(null=True)),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'OTP Authentication',
                'verbose_name_plural': 'OTP Authentication',
                'db_table': 'otp_authentication',
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=UserAuth.utils.generate_recovery_codes, max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Recovery Code',
                'verbose_name_plural': 'Recovery Codes',
                'db_table': 'recovery_codes',
            },
        ),
        migrations.AddIndex(
            model_name='authentication',
            index=models.Index(fields=['user'], name='authenticat_user_id_bbb66d_idx'),
        ),
        migrations.AddIndex(
            model_name='hotpauthentication',
            index=models.Index(fields=['authentication'], name='hotp_authen_authent_5146aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotpauthentication',
            unique_together={('authentication', 'name')},
        ),
        migrations.AddIndex(
            model_name='otpauthentication',
            index=models.Index(fields=['authentication'], name='otp_authent_authent_12acaf_idx'),
        ),
    ]
