# Generated by Django 5.1.2 on 2024-10-28 18:01

import django.utils.timezone
import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpauthentication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotpauthentication',
            name='failed_for',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotpauthentication',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotpauthentication',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotpauthentication',
            name='secret',
            field=models.CharField(default=pyotp.random_base32, editable=False, max_length=128),
        ),
    ]
