# Generated by Django 5.1.5 on 2025-01-19 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondStepVerificationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('otp_2fa_enabled', models.BooleanField(default=False)),
                ('is_recovery_generated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Second Step Verification',
                'verbose_name_plural': 'Second Step Verifications',
                'db_table': 'secondstep_verification',
            },
        ),
        migrations.RemoveIndex(
            model_name='hotpauthentication',
            name='hotp_authen_authent_5146aa_idx',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='is_recovery_generated',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='otp_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='recovery_email',
        ),
        migrations.RemoveField(
            model_name='recoverycode',
            name='authentication',
        ),
        migrations.AddField(
            model_name='authentication',
            name='default_method',
            field=models.CharField(choices=[(None, 'No Default'), (1, 'Password'), (2, 'Pass Key'), (3, 'Google Social Sign in'), (4, 'Facebook Sign in'), (5, 'Apple Sign in')], db_column='default_authentication_method', default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondstepverificationconfig',
            name='authentication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondstep_verification', to='UserAuth.authentication'),
        ),
        migrations.AlterUniqueTogether(
            name='hotpauthentication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hotpauthentication',
            name='second_step_config',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hotp_authentications', to='UserAuth.secondstepverificationconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recoverycode',
            name='second_step_config',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='UserAuth.secondstepverificationconfig'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotpauthentication',
            unique_together={('second_step_config', 'name')},
        ),
        migrations.AddIndex(
            model_name='hotpauthentication',
            index=models.Index(fields=['second_step_config'], name='hotp_authen_second__83eabb_idx'),
        ),
        migrations.AddIndex(
            model_name='secondstepverificationconfig',
            index=models.Index(fields=['authentication'], name='secondstep__authent_0ab2f4_idx'),
        ),
        migrations.RemoveField(
            model_name='hotpauthentication',
            name='authentication',
        ),
    ]
