# Generated by Django 5.1.2 on 2024-10-29 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_hotpauthentication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpauthentication',
            name='last_used',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='otpauthentication',
            name='otp_purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Verify Email'), (2, 'Second Step Verification')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IncompleteLoginSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_session', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Incomplete Login Session',
                'verbose_name_plural': 'Incomplete Login Sessions',
                'db_table': 'incomplete_sessions',
            },
        ),
    ]
