# Generated by Django 5.1.5 on 2025-01-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_secondstepverificationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondstepverificationconfig',
            name='email_verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='secondstepverificationconfig',
            name='hotp_verfication_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
