# Generated by Django 5.1.5 on 2025-01-28 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_secondstepverificationconfig_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authentication',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='default_method',
            field=models.CharField(choices=[(None, 'No Default'), ('password', 'Password'), ('passkey', 'Pass Key'), ('google', 'Google Social Sign in'), ('facebook', 'Facebook Sign in'), ('apple', 'Apple Sign in')], db_column='default_authentication_method', max_length=128),
        ),
        migrations.CreateModel(
            name='GoogleAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sign_count', models.IntegerField(default=0)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleauthn_credentials', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Google Authn Credential',
                'verbose_name_plural': 'Google Authn Credentials',
                'db_table': 'googleauthn_credential',
                'indexes': [models.Index(fields=['authentication'], name='googleauthn_authent_2e808f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_id', models.CharField(unique=True)),
                ('credential_id_byte', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('sign_count', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=120)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Web Authn Credential',
                'verbose_name_plural': 'Web Authn Credentials',
                'db_table': 'webauthn_credential',
                'indexes': [models.Index(fields=['authentication'], name='webauthn_cr_authent_0d7afe_idx')],
            },
        ),
    ]
