# Generated by Django 5.1.2 on 2024-10-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_hotpauthentication_last_used_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotpauthentication',
            unique_together={('authentication', 'name')},
        ),
    ]
