# Generated by Django 5.1.5 on 2025-01-29 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_authentication_email_authentication_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthentications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(choices=[('google', 'Google Social Sign in'), ('facebook', 'Facebook Sign in'), ('microsoft', 'Microsoft Sign in')], max_length=255)),
                ('sign_count', models.IntegerField(default=0)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googleauthn_credentials', to='UserAuth.authentication')),
            ],
            options={
                'verbose_name': 'Social Authn Credential',
                'verbose_name_plural': 'Social Authn Credentials',
                'db_table': 'socialauthn_credential',
            },
        ),
        migrations.DeleteModel(
            name='GoogleAuthnCredential',
        ),
        migrations.AddIndex(
            model_name='socialauthentications',
            index=models.Index(fields=['authentication'], name='socialauthn_authent_5e157d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialauthentications',
            unique_together={('authentication', 'account')},
        ),
    ]
